name: jaguar_shelf
description: 'Shelf integration for Jaguar. Use shelf handlers and middleware in Jaguar'
version: 0.0.1
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_shelf

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  jaguar: '>=0.3.2 <0.4.0'
  shelf: ^0.6.7+2

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
